// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD47XXUdgweBCLi3ZOCVE-MJVY8QsQNyeQ',
    appId: '1:868931261169:web:130ff405f609000002cf50',
    messagingSenderId: '868931261169',
    projectId: 'fluttertest-15e1a',
    authDomain: 'fluttertest-15e1a.firebaseapp.com',
    databaseURL: 'https://fluttertest-15e1a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttertest-15e1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMRRMQeg--fv2XR-GZLwLwVr0ajLFja3k',
    appId: '1:868931261169:android:7760a9cfa758056302cf50',
    messagingSenderId: '868931261169',
    projectId: 'fluttertest-15e1a',
    databaseURL: 'https://fluttertest-15e1a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttertest-15e1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkv7PBz1F5lrMNgwgQBuGIYpHMGMxlnzY',
    appId: '1:868931261169:ios:ec5a3bb14f7701be02cf50',
    messagingSenderId: '868931261169',
    projectId: 'fluttertest-15e1a',
    databaseURL: 'https://fluttertest-15e1a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluttertest-15e1a.appspot.com',
    iosBundleId: 'com.example.helloWorldChenFlutterTest',
  );
}
